name: 'yuzu-test-workflow'
run-name: 'Test Workflow'

on:
  workflow_dispatch:
    inputs:
      optimizationFlag:
        description: 'optimizationFlag'
        required: true
        default: 'AVX2'
        type: choice
        options:
        - SSE
        - SSE2
        - AVX
        - AVX2
        - AVX512
      yuzu_use_qt_web_engine:
        description: 'YUZU_USE_QT_WEB_ENGINE'
        required: true
        default: false
        type: boolean
      use_discord_presence:
        description: 'USE_DISCORD_PRESENCE'
        required: true
        default: false
        type: boolean
      enable_cubeb:
        description: 'ENABLE_CUBEB'
        required: true
        default: false
        type: boolean
      enable_libusb:
        description: 'ENABLE_LIBUSB'
        required: true
        default: false
        type: boolean
      enable_web_service:
        description: 'ENABLE_WEB_SERVICE'
        required: true
        default: false
        type: boolean
      yuzu_room:
        description: 'YUZU_ROOM'
        required: true
        default: false
        type: boolean
      yuzu_crash_dumps:
        description: 'YUZU_CRASH_DUMPS'
        required: true
        default: false
        type: boolean

jobs:
  build-msvc:
    name: 'build (windows, msvc)'

    runs-on: windows-2022
    steps:
      - name: Log the inputs
        shell: pwsh
        run: |
          echo "optimizationFlag: $env:OPTIMIZATIONFLAG"
          echo -G "Visual Studio 17 2022" -A x64 -DCMAKE_POLICY_DEFAULT_CMP0069=NEW -DYUZU_ENABLE_LTO=ON -DYUZU_USE_BUNDLED_QT=1 -DYUZU_USE_BUNDLED_SDL2=1 -DYUZU_USE_QT_WEB_ENGINE=$env:YUZU_USE_QT_WEB_ENGINE -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON -DYUZU_ENABLE_COMPATIBILITY_REPORTING=OFF -DYUZU_TESTS=OFF -DUSE_DISCORD_PRESENCE=$env:USE_DISCORD_PRESENCE -DENABLE_QT_TRANSLATION=ON -DDISPLAY_VERSION="early-access" -DCMAKE_BUILD_TYPE=Release -DYUZU_CRASH_DUMPS=$env:YUZU_CRASH_DUMPS -DENABLE_CUBEB=$env:ENABLE_CUBEB -DENABLE_LIBUSB=$env:ENABLE_LIBUSB -DENABLE_WEB_SERVICE=$env:ENABLE_WEB_SERVICE -DYUZU_ROOM=$env:YUZU_ROOM ..
        env:
          YUZU_USE_QT_WEB_ENGINE: ${{ inputs.yuzu_use_qt_web_engine }}
          USE_DISCORD_PRESENCE: ${{ inputs.use_discord_presence }}
          ENABLE_CUBEB: ${{ inputs.enable_cubeb }}
          ENABLE_LIBUSB: ${{ inputs.enable_libusb }}
          ENABLE_WEB_SERVICE: ${{ inputs.enable_web_service }}
          YUZU_ROOM: ${{ inputs.yuzu_room }}
          YUZU_CRASH_DUMPS: ${{ inputs.yuzu_crash_dumps }}
