name: 'yuzu-patch'
run-name: 'Patch yuzu'

on:
  workflow_dispatch:

jobs:
  build-msvc:
    name: 'build (windows, msvc)'

    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        name: Checkout yuzu
        with:
          repository: yuzu-emu/yuzu
          fetch-depth: 0
      - uses: actions/checkout@v3
        name: Checkout patches
        with:
          path: 'patches'
          fetch-depth: 0
      - name: Do the patching
        shell: pwsh
        run: |
          git status
          git apply .\patches\patches\cmakelists.patch
          git status
